#!/usr/bin/env python3
"""DevFlow Analytics Dashboard Generator.

Reads all story memories from Automation/.memory/devflow/stories/*.json
and optional report JSONs from Automation/reports/*/automation-report.json,
then generates a self-contained HTML analytics dashboard.

Output: Automation/docs/devflow-analytics.html

Usage:
    python3 Automation/scripts/generate_analytics.py
    # Then open: http://localhost:8080/devflow-analytics.html
"""
from __future__ import annotations

import json
import glob
import os
import sys
import time
from pathlib import Path
from datetime import datetime
from typing import Any


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[2]
AUTO_DIR  = Path(__file__).resolve().parents[1]
STORIES_DIR        = AUTO_DIR / ".memory" / "devflow" / "stories"
REPORTS_DIR        = AUTO_DIR / "reports"
OUT_HTML           = AUTO_DIR / "docs" / "devflow-analytics.html"
FEATURE_CACHE_FILE = AUTO_DIR / ".memory" / "feature-cache" / "pi-snapshot.json"
FEATURE_CACHE_TTL  = 3600   # 1 hour — matches sync_jira_features.py

# ---------------------------------------------------------------------------
# Stories that should always be shown as "Cancelled" regardless of Jira status.
# Add/remove keys here; this list persists across pi-snapshot cache refreshes.
# ---------------------------------------------------------------------------
CANCELLED_STORY_KEYS: set[str] = {
    "BDATART-822",
    "BDATART-818",
    "BDATART-821",
    "BDATART-824",
}


# ---------------------------------------------------------------------------
# Load .env.local so JIRA_BASE_URL is available without manual export
# ---------------------------------------------------------------------------

def _load_env() -> None:
    env_path = AUTO_DIR / ".env.local"
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:   # don't overwrite shell env
            os.environ[key] = value

_load_env()


# ---------------------------------------------------------------------------
# Auto-detect project info — works in ANY repo
# ---------------------------------------------------------------------------

def auto_project_info() -> dict[str, str]:
    """Detect project name, short badge, language, and stack from memory files.

    Detection order:
      1. Automation/.memory/project-profile.json   — generated by setup_project.py
      2. Automation/.memory/repo-config.json        — repo root path
      3. AGENTS.md / README.md                      — fallback name from heading
      4. repo folder name                           — last resort
    """
    info: dict[str, str] = {
        "name": "",          # Full project name  e.g. "cdp-linking-middleware"
        "short": "",         # Badge label        e.g. "CDP-LMW"
        "language": "",      # e.g. "java"
        "label": "",         # e.g. "Spring Boot (Maven)"
        "category": "",      # e.g. "backend"
        "repo_root": str(REPO_ROOT),
    }

    # ── 1. project-profile.json ───────────────────────────────────────────────
    profile_path = AUTO_DIR / ".memory" / "project-profile.json"
    if profile_path.exists():
        try:
            profile = json.loads(profile_path.read_text(encoding="utf-8"))
            info["language"] = profile.get("language") or ""
            info["label"]    = profile.get("label") or ""
            info["category"] = profile.get("category") or ""
            rr = profile.get("repo_root") or ""
            if rr:
                info["name"] = Path(rr).name
        except Exception:
            pass

    # ── 2. repo-config.json ───────────────────────────────────────────────────
    config_path = AUTO_DIR / ".memory" / "repo-config.json"
    if config_path.exists() and not info["name"]:
        try:
            cfg = json.loads(config_path.read_text(encoding="utf-8"))
            rr = cfg.get("repo_root") or ""
            if rr:
                info["name"] = Path(rr).name
        except Exception:
            pass

    # ── 3. Fallback to actual repo folder name ────────────────────────────────
    if not info["name"]:
        info["name"] = REPO_ROOT.name

    # ── Build short badge from name ───────────────────────────────────────────
    # "cdp-linking-middleware" → "CDP-LMW"
    # "my-backend-service"    → "MBS"
    # "frontend-app"          → "FE-APP"
    name = info["name"]
    parts = [p for p in name.replace("_", "-").split("-") if p]
    # Build short code: "cdp-linking-middleware" → "CDP-LMW"
    # Strategy: first part + initials of remaining parts
    if len(parts) >= 2:
        first = parts[0].upper()
        rest  = "".join(p[0].upper() for p in parts[1:])
        candidate = f"{first}-{rest}"
        info["short"] = candidate[:10]  # cap at 10 chars
    elif parts:
        info["short"] = parts[0][:6].upper()
    else:
        info["short"] = name[:6].upper()

    return info


# Cache so we don't reload on every row
_PROJECT_INFO: dict[str, str] | None = None

def project_info() -> dict[str, str]:
    global _PROJECT_INFO
    if _PROJECT_INFO is None:
        _PROJECT_INFO = auto_project_info()
    return _PROJECT_INFO


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

STAGE_ORDER = [
    "start",
    "apply_story_update",
    "after_story_approval",
    "after_code_changes",
    "preview_mr",
    "create_mr",
]

STAGE_PROGRESS = {s: i for i, s in enumerate(STAGE_ORDER)}

STATUS_FROM_STAGE = {
    "start":               ("In Progress",  "#238636", "#2ea043"),
    "apply_story_update":  ("Jira Updated", "#1f6feb", "#388bfd"),
    "after_story_approval":("Coding",       "#9e6a03", "#d29922"),
    "after_code_changes":  ("Tests Done",   "#1f6feb", "#388bfd"),
    "preview_mr":          ("MR Preview",   "#8957e5", "#a371f7"),
    "create_mr":           ("PR Created",   "#238636", "#3fb950"),
}


def _fmt_duration(seconds: float) -> str:
    if seconds <= 0:
        return "—"
    if seconds < 60:
        return f"{seconds:.0f}s"
    m, s = divmod(int(seconds), 60)
    if m < 60:
        return f"{m}m {s}s"
    h, m2 = divmod(m, 60)
    return f"{h}h {m2}m"


def _parse_date(s: str) -> str:
    """Return a short human date from ISO string."""
    if not s:
        return "—"
    try:
        dt = datetime.fromisoformat(s.replace("Z", "+00:00"))
        return dt.strftime("%b %d, %Y")
    except Exception:
        return s[:10]


def _jira_url(story_id: str) -> str:
    base = os.getenv("JIRA_BASE_URL", "").rstrip("/")
    if base:
        return f"{base}/browse/{story_id}"
    return f"https://jira.atlassian.com/browse/{story_id}"


def _live_jira_enabled() -> bool:
    value = (os.getenv("AUTOMATION_ANALYTICS_LIVE_JIRA") or "1").strip().lower()
    return value not in {"0", "false", "no", "off", "disabled"}


def _bucket_feature_stories(stories: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]]]:
    completed: list[dict[str, Any]] = []
    in_progress: list[dict[str, Any]] = []
    pending: list[dict[str, Any]] = []
    for story in stories:
        status_category = (story.get("status_category") or "").lower()
        status = (story.get("status") or "").lower()
        if status_category == "done" or status in {"done", "closed", "resolved"}:
            completed.append(story)
        elif status_category == "in progress":
            in_progress.append(story)
        else:
            pending.append(story)
    return completed, in_progress, pending


def _enrich_feature_context_from_jira(jira_client: Any, feature: dict[str, Any]) -> dict[str, Any]:
    """Load full sibling story details so the tree can show story subtasks."""
    if not feature.get("ok"):
        return feature

    enriched: list[dict[str, Any]] = []
    for item in feature.get("sibling_stories") or []:
        key = item.get("key")
        if not key:
            continue
        try:
            full = jira_client.read_issue(key)
            merged = {**item, **full}
            enriched.append(merged)
        except Exception:
            enriched.append(item)

    if not enriched:
        return feature

    completed, in_progress, pending = _bucket_feature_stories(enriched)
    feature = dict(feature)
    feature.update(
        {
            "sibling_stories": enriched,
            "completed_stories": completed,
            "in_progress_stories": in_progress,
            "pending_stories": pending,
            "completed_count": len(completed),
            "total_sibling_count": len(enriched),
        }
    )
    return feature


def _refresh_from_jira(jira_id: str) -> tuple[dict[str, Any], dict[str, Any], str]:
    """Read the latest story and Feature tree directly from Jira.

    The dashboard should reflect the Jira board each time it is generated. If
    Jira is unreachable, callers fall back to local memory and show the stale
    data instead of failing the whole report.
    """
    if not _live_jira_enabled():
        return {}, {}, "Live Jira refresh disabled by AUTOMATION_ANALYTICS_LIVE_JIRA."

    jira_src = AUTO_DIR / "mcp-servers" / "jira-mcp" / "src"
    if str(jira_src) not in sys.path:
        sys.path.insert(0, str(jira_src))
    try:
        import jira_client  # type: ignore

        story = jira_client.read_issue(jira_id)
        feature = jira_client.feature_context_for_story(story)
        feature = _enrich_feature_context_from_jira(jira_client, feature)
        return story, feature, ""
    except Exception as exc:
        return {}, {}, f"Live Jira refresh failed: {exc}"


def _safe_dom_id(value: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in value)


def _merge_unique_issues(existing: list[dict[str, Any]], incoming: list[dict[str, Any]]) -> list[dict[str, Any]]:
    merged: dict[str, dict[str, Any]] = {}
    for item in existing + incoming:
        key = item.get("key")
        if key:
            merged[key] = item
    return list(merged.values())


def _story_from_feature_context(jira_id: str, fc: dict[str, Any]) -> dict[str, Any]:
    for item in fc.get("sibling_stories") or []:
        if item.get("key") == jira_id:
            return item
    for bucket in ("completed_stories", "in_progress_stories", "pending_stories"):
        for item in fc.get(bucket) or []:
            if item.get("key") == jira_id:
                return item
    return {}


def _fallback_feature_context(raw: dict[str, Any], story: dict[str, Any]) -> dict[str, Any]:
    """Build the best tree context possible from locally stored data.

    DevFlow now stores the full story, but older memory files may only contain a
    failed feature lookup. This fallback lets the dashboard still show the
    parent Feature row when the story payload contains parent fields.
    """
    fc = raw.get("feature_context") or {}
    if fc.get("ok") or (fc.get("feature") or {}).get("key"):
        return fc

    parent_key = story.get("parent") or raw.get("feature_key") or ""
    if not parent_key:
        return fc

    parent_summary = story.get("parent_summary") or parent_key
    parent_status = story.get("parent_status") or ""
    status_category = story.get("status_category") or ""
    story_status = story.get("status") or "To Do"
    current = {
        "key": story.get("key") or raw.get("jira_id") or "",
        "summary": story.get("summary") or "",
        "status": story_status,
        "status_category": status_category,
        "issue_type": story.get("issue_type") or "Story",
        "assignee": story.get("assignee") or "—",
        "priority": story.get("priority") or "",
        "updated": story.get("updated") or "",
    }
    completed = [current] if status_category.lower() == "done" or story_status.lower() in {"done", "closed", "resolved"} else []
    in_progress = [current] if status_category.lower() == "in progress" else []
    pending = [] if completed or in_progress else [current]
    return {
        "ok": True,
        "story_key": current["key"],
        "feature": {
            "key": parent_key,
            "name": parent_summary,
            "issue_type": story.get("parent_issue_type") or "Feature",
            "status": parent_status,
            "description": "",
            "acceptance_criteria": [],
        },
        "feature_goal": parent_summary,
        "current_story_fit": f'{current["key"]} contributes to {parent_key} by delivering: {current["summary"]}.',
        "sibling_stories": [current],
        "completed_stories": completed,
        "in_progress_stories": in_progress,
        "pending_stories": pending,
        "completed_count": len(completed),
        "total_sibling_count": 1,
        "search_error": "Sibling list not available in old local memory; run DevFlow start again to refresh full Feature context.",
        "rule": "Feature context inferred from the stored story parent fields.",
    }


def load_story(path: Path) -> dict[str, Any] | None:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None

    jira_id    = raw.get("jira_id") or path.stem.upper()
    stage      = raw.get("stage") or "start"
    live_story, live_fc, live_error = _refresh_from_jira(jira_id)
    if live_story:
        raw.update(
            {
                "jira_id": jira_id,
                "story": live_story,
                "story_updated": live_story.get("updated"),
                "feature_context": live_fc,
                "feature_key": ((live_fc.get("feature") or {}).get("key") if live_fc else raw.get("feature_key")),
                "jira_refresh_updated_at_epoch": int(time.time()),
            }
        )
        try:
            path.write_text(json.dumps(raw, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
        except OSError:
            pass
    story_raw  = live_story or raw.get("story") or {}
    fc         = live_fc or _fallback_feature_context(raw, story_raw)
    live_status = "fresh" if live_story else ("disabled" if not _live_jira_enabled() else "fallback")
    feat       = fc.get("feature") or {}
    ca         = raw.get("codebase_analysis") or {}
    timings    = raw.get("stage_timings") or []
    updated    = story_raw.get("updated") or raw.get("story_updated") or raw.get("updated_at") or ""
    next_gate  = raw.get("next_gate") or ""
    mr_result  = raw.get("mr_result") or {}

    ai_s   = sum(t.get("elapsed_s", 0) for t in timings if t.get("actor") == "ai")
    hu_s   = sum(t.get("elapsed_s", 0) for t in timings if t.get("actor") == "human")
    approvals = sum(1 for t in timings if t.get("actor") == "human")

    # Try loading report JSON for richer data
    report: dict[str, Any] = {}
    report_path = REPORTS_DIR / jira_id / "automation-report.json"
    if report_path.exists():
        try:
            report = json.loads(report_path.read_text(encoding="utf-8"))
        except Exception:
            pass

    mr_url   = report.get("mr_url") or mr_result.get("web_url") or ""
    mr_title = report.get("mr_title") or ""
    files_changed = report.get("files_changed") or []
    test_ok  = (report.get("test_result") or {}).get("ok")

    # Derive status
    status_info = STATUS_FROM_STAGE.get(stage, ("In Progress", "#1f6feb", "#388bfd"))
    if stage == "create_mr" and mr_url:
        status_info = ("PR Created", "#238636", "#3fb950")

    progress_pct = int((STAGE_PROGRESS.get(stage, 0) / max(len(STAGE_ORDER) - 1, 1)) * 100)

    feature_key     = feat.get("key") or raw.get("feature_key") or ""
    feature_name    = feat.get("name") or feat.get("summary") or ""
    feature_status  = feat.get("status") or ""
    feature_desc    = (feat.get("description") or "")[:200]
    completed_siblings = fc.get("completed_count") or 0

    # Full sibling story lists for tree view
    all_siblings      = fc.get("sibling_stories") or []
    completed_stories = fc.get("completed_stories") or []
    in_progress_stories = fc.get("in_progress_stories") or []
    pending_stories   = fc.get("pending_stories") or []

    # Current story values. Prefer the full stored story, then sibling context,
    # then the generated story id so the tree never renders a blank row.
    current_from_context = _story_from_feature_context(jira_id, fc)
    own_summary = story_raw.get("summary") or current_from_context.get("summary") or jira_id
    own_status = story_raw.get("status") or current_from_context.get("status") or status_info[0]
    own_status_category = story_raw.get("status_category") or current_from_context.get("status_category") or ""
    own_assignee = story_raw.get("assignee") or current_from_context.get("assignee") or "—"

    # ── Real Jira status overrides DevFlow stage label for table & tree ────────
    # Use actual Jira status so table shows "Done" not "In Progress" for a
    # story that is Done in Jira but only reached stage=start in DevFlow.
    _jira_status_colors = {
        "done":         ("#1a4731", "#3fb950"),
        "in progress":  ("#1f3a6e", "#388bfd"),
        "in analysis":  ("#2a2200", "#d29922"),
        "pr created":   ("#1a4731", "#3fb950"),
        "ready":        ("#1a3a4a", "#58a6ff"),
        "draft":        ("#21262d", "#8b949e"),
        "to do":        ("#21262d", "#8b949e"),
    }
    _s_lower = (own_status or "").lower()
    _bg, _fg = next(
        (v for k, v in _jira_status_colors.items() if k in _s_lower),
        ("#21262d", "#8b949e")
    )
    # For MR created, always show green
    if stage == "create_mr" and mr_url:
        own_status = "PR Created"
        _bg, _fg = "#1a4731", "#3fb950"

    return {
        "id": jira_id,
        "summary": own_summary,
        "jira_status": own_status,
        "jira_status_category": own_status_category,
        "assignee": own_assignee,
        "feature_key": feature_key,
        "feature_name": feature_name,
        "feature_status": feature_status,
        "feature_desc": feature_desc,
        "stage": stage,
        "stage_timings": timings,
        "status_label": own_status,      # ← real Jira status (Done / In Progress / In Analysis)
        "status_bg": _bg,
        "status_color": _fg,
        "confidence": ca.get("confidence") or "—",
        "updated": _parse_date(updated),
        "ai_time": _fmt_duration(ai_s),
        "human_time": _fmt_duration(hu_s),
        "approvals": approvals,
        "files_changed": len(files_changed),
        "files_list": files_changed[:20],
        "test_verdict": "passed" if test_ok else ("failed" if test_ok is False else "—"),
        "mr_url": mr_url,
        "mr_title": mr_title,
        "next_gate": next_gate,
        "progress_pct": progress_pct,
        "completed_siblings": completed_siblings,
        "jira_url": _jira_url(jira_id),
        "raw_ai_s": ai_s,
        "subtasks": story_raw.get("subtasks") or [],
        "live_jira_status": live_status,
        "live_jira_error": live_error,
        # Tree data
        "completed_stories": completed_stories,
        "in_progress_stories": in_progress_stories,
        "pending_stories": pending_stories,
        "all_siblings": all_siblings,
    }


def load_all_stories() -> list[dict[str, Any]]:
    stories = []
    for path in sorted(STORIES_DIR.glob("*.json")):
        s = load_story(path)
        if s:
            stories.append(s)
    return sorted(stories, key=lambda x: x.get("updated") or "", reverse=True)


# ---------------------------------------------------------------------------
# Tree view builder
# ---------------------------------------------------------------------------

STAGE_LABELS = {
    "start":                "📥 Start — Jira + Codebase Fetched",
    "apply_story_update":   "✏️  Jira Story Updated",
    "after_story_approval": "🌿 Branch Created",
    "after_code_changes":   "🧪 Tests / Validation Done",
    "preview_mr":           "👀 MR Preview Reviewed",
    "create_mr":            "🚀 MR Created & Pushed",
}

STATUS_ICON = {
    "Done":        ("✅", "#3fb950"),
    "In Progress": ("🔵", "#388bfd"),
    "To Do":       ("⏳", "#8b949e"),
    "Implementing":("🔧", "#d29922"),
    "PR Created":  ("🚀", "#3fb950"),
    "Coding":      ("💻", "#d29922"),
    "Cancelled":   ("🚫", "#6e7681"),
    "default":     ("▸",  "#8b949e"),
}


def _status_icon(status: str) -> tuple[str, str]:
    for k, v in STATUS_ICON.items():
        if k.lower() in status.lower():
            return v
    return STATUS_ICON["default"]


def _sibling_row(s: dict[str, Any], is_current: bool = False, jira_url: str = "") -> str:
    key      = s.get("key") or "?"
    summary  = s.get("summary") or "—"
    status   = s.get("status") or "To Do"
    assignee = s.get("assignee") or ""
    updated  = _parse_date(s.get("updated") or "")
    icon, color = _status_icon(status)
    url = jira_url or _jira_url(key)

    # Clean up "unassigned" → "—"
    if not assignee or assignee.lower() in ("unassigned", "none", "null", ""):
        assignee = "—"

    # Detect cross-project stories using Jira prefix, not repo name
    # e.g. BDRSP-* is main project, BDATART-* is cross-project
    jira_prefix = os.getenv("JIRA_PROJECT_KEY", "").upper()
    if not jira_prefix:
        # Auto-detect: find most common prefix in .memory/devflow/stories/
        try:
            import glob as _glob
            _keys = [Path(p).stem.split("-")[0].upper()
                     for p in _glob.glob(str(AUTO_DIR / ".memory" / "devflow" / "stories" / "*.json"))]
            from collections import Counter as _Counter
            if _keys:
                jira_prefix = _Counter(_keys).most_common(1)[0][0]
        except Exception:
            pass
    key_prefix = key.split("-")[0].upper()
    is_cross_project = bool(jira_prefix) and key_prefix != jira_prefix

    # Cross-project stories get muted styling
    if is_cross_project and not is_current:
        opacity = "opacity:.55;"
        proj_pill = (f'<span style="background:#21262d;color:#8b949e;border:1px solid #30363d;'
                     f'padding:1px 6px;border-radius:8px;font-size:.7rem;">{key_prefix}</span>')
    else:
        opacity = ""
        proj_pill = ""

    # Highlight = In Progress in Jira (blue left border), NOT DevFlow badge
    is_in_progress = "in progress" in status.lower()
    highlight = f"border-left:3px solid #388bfd;" if is_in_progress else ""
    devflow_badge = ('<span style="background:#1a2a4a;color:#58a6ff;border:1px solid #1f6feb;'
                     'padding:1px 7px;border-radius:10px;font-size:.72rem;margin-left:6px;">DevFlow</span>'
                     if is_current else "")

    return f'''
    <div class="tree-sibling" style="{highlight}{opacity}">
      <span style="color:{color};margin-right:4px;">{icon}</span>
      {proj_pill}
      <a href="{url}" target="_blank" class="tree-key">{key}</a>
      {devflow_badge}
      <span class="tree-summary">{summary[:80]}{"…" if len(summary)>80 else ""}</span>
      <span class="tree-meta">{status} · {assignee} · {updated}</span>
    </div>'''


def _clean_assignee(val: str | None) -> str:
    """Return '—' for unassigned/null values, otherwise the name."""
    if not val or val.lower() in ("unassigned", "none", "null", ""):
        return "—"
    return val


def _current_user_display_name(pi: dict[str, Any]) -> str:
    """Derive the current developer's Jira display name.

    All stories in the pi-snapshot were fetched with assignee = JIRA_USERNAME,
    so the first non-empty assignee display name found IS the current user.
    Falls back to the JIRA_USERNAME env var (email) if the snapshot is empty.
    """
    for s in pi.get("unparented") or []:
        a = s.get("assignee") or ""
        if a and a.lower() not in ("unassigned", "none", "null", "—", ""):
            return a
    for feat in (pi.get("features") or {}).values():
        for s in feat.get("stories") or []:
            a = s.get("assignee") or ""
            if a and a.lower() not in ("unassigned", "none", "null", "—", ""):
                return a
    return os.getenv("JIRA_USERNAME", "")


def _is_my_story(sib: dict[str, Any], current_user: str, devflow_ids: set[str]) -> bool:
    """True if this story belongs to the current developer or is DevFlow-tracked."""
    if sib.get("key", "") in devflow_ids:
        return True
    if not current_user:
        return True   # no user info → show all
    assignee = (sib.get("assignee") or "").strip()
    return assignee.lower() == current_user.lower()


def _subtask_tree_nodes(subtasks: list[dict[str, Any]]) -> str:
    """Render subtasks as always-visible child tree nodes under a story."""
    if not subtasks:
        return ""
    rows = ""
    for i, sub in enumerate(subtasks):
        sub_status = sub.get("status") or "—"
        sub_icon, sub_color = _status_icon(sub_status)
        sub_key = sub.get("key") or "?"
        sub_summary = (sub.get("summary") or "—")[:110]
        connector = "└─" if i == len(subtasks) - 1 else "├─"
        rows += f'''
    <div class="subtask-tree-node">
      <span class="subtask-connector">{connector}</span>
      <span style="color:{sub_color};font-size:.85rem;">{sub_icon}</span>
      <a href="{_jira_url(sub_key)}" target="_blank" class="tree-key subtask-key"
         onclick="event.stopPropagation()">{sub_key}</a>
      <span class="subtask-summary">{sub_summary}</span>
      <span class="tree-meta">{sub_status}</span>
    </div>'''
    return rows


def _story_node(sib: dict[str, Any], *, df_story: dict[str, Any] | None = None) -> str:
    key = sib.get("key") or (df_story or {}).get("id") or "?"
    story_id = f"story_{_safe_dom_id(key)}"
    summary = sib.get("summary") or (df_story or {}).get("summary") or "—"
    status = sib.get("status") or (df_story or {}).get("jira_status") or "To Do"
    # Always override with "Cancelled" for stories in the cancelled list
    if key in CANCELLED_STORY_KEYS:
        status = "Cancelled"
    assignee = _clean_assignee(sib.get("assignee") or (df_story or {}).get("assignee"))
    updated = _parse_date(sib.get("updated") or (df_story or {}).get("updated") or "")
    icon, color = _status_icon(status)
    is_devflow = df_story is not None

    # Highlight only if story is genuinely "In Progress"
    is_in_progress = "in progress" in status.lower()
    highlight_style = "border-left:3px solid #388bfd;background:rgba(56,139,253,.06);" if is_in_progress else ""

    devflow_badge = '<span class="devflow-badge">DevFlow</span>' if is_devflow else ""

    # ── Subtasks: prefer pi-snapshot data, fall back to DevFlow story subtasks ─
    subtasks: list[dict[str, Any]] = (
        sib.get("subtasks")
        or (df_story or {}).get("subtasks")
        or []
    )
    subtask_nodes = _subtask_tree_nodes(subtasks)

    # ── DevFlow stage summary (only for DevFlow stories) ─────────────────────
    devflow_detail = ""
    if is_devflow and df_story:
        mr_url   = df_story.get("mr_url") or ""
        next_gate = df_story.get("next_gate") or ""
        ai_time  = df_story.get("ai_time") or "—"
        test_v   = df_story.get("test_verdict") or "—"
        test_color = "#3fb950" if test_v == "passed" else "#f85149" if test_v == "failed" else "#8b949e"
        mr_html = ""
        if mr_url:
            mr_html = f'<div class="detail-item" style="margin-left:22px;">🔗 <a href="{mr_url}" target="_blank" style="color:#58a6ff;">MR</a></div>'
        elif next_gate:
            mr_html = f'<div class="detail-item" style="margin-left:22px;">⏸ <span style="color:#d29922;font-size:.78rem;">{next_gate}</span></div>'
        devflow_detail = f'''
    <div style="display:flex;gap:14px;flex-wrap:wrap;padding:4px 4px 4px 22px;font-size:.78rem;color:#8b949e;">
      <span>🤖 AI: <b style="color:#a371f7;">{ai_time}</b></span>
      <span>🧪 Tests: <b style="color:{test_color};">{test_v}</b></span>
      {mr_html}
    </div>'''

    # ── Children content: subtasks + devflow summary ──────────────────────────
    has_children = bool(subtask_nodes or devflow_detail)
    toggle_icon  = "▶" if has_children else "▸"
    children_div = ""
    if has_children:
        children_div = f'''
      <div class="story-children" id="children_{story_id}" style="display:none">
        <div class="subtasks-container">{subtask_nodes}</div>
        {devflow_detail}
      </div>'''

    return f'''
    <div class="story-node" id="{story_id}" style="{highlight_style}">
      <div class="story-header" onclick="{'toggleTree(' + chr(39) + story_id + chr(39) + ')' if has_children else ''}">
        <span class="tree-toggle" id="toggle_{story_id}">{toggle_icon}</span>
        <span style="color:{color};margin-right:4px;">{icon}</span>
        <a href="{_jira_url(key)}" target="_blank" class="tree-key"
           onclick="event.stopPropagation()">{key}</a>
        {devflow_badge}
        <span class="tree-summary">{summary[:110]}{"…" if len(summary) > 110 else ""}</span>
        <span class="tree-meta">{status} · {assignee} · {updated}</span>
      </div>{children_div}
    </div>'''


def _plain_story_detail(sib: dict[str, Any]) -> str:
    key = sib.get("key") or "?"
    status = sib.get("status") or "—"
    assignee = _clean_assignee(sib.get("assignee"))
    priority = sib.get("priority") or "—"
    subtasks = sib.get("subtasks") or []
    return f'''
    <div class="story-detail-tree">
      <div class="detail-grid">
        <div class="detail-item">📌 Status: <b>{status}</b></div>
        <div class="detail-item">👤 Assignee: <b>{assignee}</b></div>
        <div class="detail-item">🏷 Priority: <b>{priority}</b></div>
      </div>
      {_subtask_list_html(subtasks)}
    </div>'''


def _subtask_list_html(subtasks: list[dict[str, Any]]) -> str:
    if not subtasks:
        return '''
      <div class="subtask-list empty-subtasks">
        No subtasks found for this story.
      </div>'''

    rows = ""
    for sub in subtasks:
        sub_status = sub.get("status") or "—"
        sub_icon, sub_color = _status_icon(sub_status)
        sub_key = sub.get("key") or "?"
        rows += f'''
        <div class="subtask-row">
          <span class="subtask-indent">└─</span>
          <span style="color:{sub_color};">{sub_icon}</span>
          <a href="{_jira_url(sub_key)}" target="_blank" class="tree-key">{sub_key}</a>
          <span class="tree-summary">{(sub.get("summary") or "—")[:100]}</span>
          <span class="tree-meta">{sub_status} · {_clean_assignee(sub.get("assignee"))}</span>
        </div>'''
    return f'''
      <div class="subtask-list">
        <div class="tree-section-label">Subtasks ({len(subtasks)})</div>
        {rows}
      </div>'''


def _render_sibling_group(
    rows: list[dict[str, Any]],
    *,
    devflow_ids: set[str],
    feature_stories: list[dict[str, Any]],
    extra_subtasks: dict[str, list[dict[str, Any]]] | None = None,
) -> str:
    html = ""
    for sib in rows:
        k = sib.get("key", "")
        df_story = next((x for x in feature_stories if x["id"] == k), None) if k in devflow_ids else None
        # Merge any injected subtasks (from story-under-story parent relationships)
        if extra_subtasks and k in extra_subtasks:
            merged = dict(sib)
            existing = list(merged.get("subtasks") or [])
            injected = extra_subtasks[k]
            existing_keys = {s.get("key") for s in existing}
            merged["subtasks"] = existing + [s for s in injected if s.get("key") not in existing_keys]
            sib = merged
        html += _story_node(sib, df_story=df_story)
    return html


def _stage_row(t: dict[str, Any], is_last: bool = False) -> str:
    stage   = t.get("stage") or ""
    actor   = t.get("actor") or "ai"
    elapsed = t.get("elapsed_s") or 0
    status  = t.get("status") or "done"
    label   = STAGE_LABELS.get(stage, f"⚙ {stage}")
    dur     = _fmt_duration(elapsed)
    actor_icon = "🤖" if actor == "ai" else "👤"
    actor_color = "#58a6ff" if actor == "ai" else "#f78166"
    connector = "└─" if is_last else "├─"
    return f'''
    <div class="tree-stage">
      <span class="tree-connector">{connector}</span>
      <span class="stage-label">{label}</span>
      <span style="color:{actor_color};font-size:.75rem;margin-left:8px;">{actor_icon} {actor}</span>
      <span class="tree-meta" style="margin-left:8px;">{dur}</span>
    </div>'''


# ---------------------------------------------------------------------------
# PI snapshot helpers (from sync_jira_features.py cache)
# ---------------------------------------------------------------------------

def _pi_snapshot_valid() -> bool:
    """Return True if the pi-snapshot cache file exists and is < FEATURE_CACHE_TTL old."""
    if not FEATURE_CACHE_FILE.exists():
        return False
    try:
        data = json.loads(FEATURE_CACHE_FILE.read_text(encoding="utf-8"))
        return (time.time() - data.get("fetched_at_epoch", 0)) < FEATURE_CACHE_TTL
    except Exception:
        return False


def _refresh_pi_snapshot() -> None:
    """Trigger sync_jira_features.py in a subprocess (silent, best-effort)."""
    try:
        import subprocess
        sync_path = AUTO_DIR / "scripts" / "sync_jira_features.py"
        if sync_path.exists():
            subprocess.run(
                [sys.executable, str(sync_path), "--force"],
                capture_output=True,
                timeout=120,
            )
    except Exception:
        pass


def _load_pi_snapshot() -> dict[str, Any]:
    """Load PI snapshot, auto-refreshing from Jira if the cache is stale.

    Returns the full snapshot dict (keys: features, unparented, total_stories…).
    Falls back to an empty dict if Jira is unreachable and no cache exists.
    """
    if _live_jira_enabled() or not _pi_snapshot_valid():
        _refresh_pi_snapshot()
    try:
        if FEATURE_CACHE_FILE.exists():
            return json.loads(FEATURE_CACHE_FILE.read_text(encoding="utf-8"))
    except Exception:
        pass
    return {}


def _pi_story_bucket(pi_story: dict[str, Any]) -> str:
    """Classify a pi-snapshot story into 'completed', 'in_progress', or 'pending'."""
    sc  = (pi_story.get("status_category") or "").lower()
    sst = (pi_story.get("status") or "").lower()
    if sc == "done" or sst in {"done", "closed", "resolved"}:
        return "completed"
    if sc == "in progress":
        return "in_progress"
    return "pending"


def build_tree_html(stories: list[dict[str, Any]]) -> str:
    """Build Feature → Story → Stages/Subtasks tree structure."""

    # Group DevFlow stories by feature key
    devflow_ids = {s["id"] for s in stories}

    # ── Detect Jira project prefix from DevFlow story IDs ─────────────────────
    # Repo name (cdp-linking-middleware) != Jira prefix (BDRSP).
    # Derive from the actual story keys: "BDRSP-1413" → prefix = "BDRSP"
    jira_prefixes: set[str] = {sid.split("-")[0].upper() for sid in devflow_ids if "-" in sid}

    # If no DevFlow stories exist yet, derive prefix from env var or pi-snapshot
    # (most common key prefix = the team's primary project).
    if not jira_prefixes:
        _env_key = os.getenv("JIRA_PROJECT_KEY", "").upper()
        if _env_key:
            jira_prefixes.add(_env_key)
        else:
            # Count all key prefixes across pi-snapshot stories to find primary project
            try:
                _pi_raw = json.loads(FEATURE_CACHE_FILE.read_text(encoding="utf-8")) if FEATURE_CACHE_FILE.exists() else {}
                from collections import Counter as _Counter
                _all_keys: list[str] = []
                for _f in (_pi_raw.get("features") or {}).values():
                    _all_keys += [(s.get("key") or "").split("-")[0].upper() for s in _f.get("stories") or []]
                for _s in _pi_raw.get("unparented") or []:
                    _all_keys.append((_s.get("key") or "").split("-")[0].upper())
                _all_keys = [k for k in _all_keys if k]
                if _all_keys:
                    jira_prefixes.add(_Counter(_all_keys).most_common(1)[0][0])
            except Exception:
                pass

    def _is_same_jira_project(key: str) -> bool:
        """True if this Jira key belongs to one of the tracked projects."""
        return key.split("-")[0].upper() in jira_prefixes

    features: dict[str, dict[str, Any]] = {}
    standalone: list[dict[str, Any]] = []

    for s in stories:
        fk = s.get("feature_key") or ""
        if fk and fk != "—":
            if fk not in features:
                features[fk] = {
                    "key": fk,
                    "name": s.get("feature_name") or fk,
                    "status": s.get("feature_status") or "",
                    "desc": s.get("feature_desc") or "",
                    "stories": [],
                    "completed_stories": s.get("completed_stories") or [],
                    "in_progress_stories": s.get("in_progress_stories") or [],
                    "pending_stories": s.get("pending_stories") or [],
                }
            else:
                features[fk]["completed_stories"] = _merge_unique_issues(
                    features[fk]["completed_stories"], s.get("completed_stories") or []
                )
                features[fk]["in_progress_stories"] = _merge_unique_issues(
                    features[fk]["in_progress_stories"], s.get("in_progress_stories") or []
                )
                features[fk]["pending_stories"] = _merge_unique_issues(
                    features[fk]["pending_stories"], s.get("pending_stories") or []
                )
                if not features[fk]["status"] and s.get("feature_status"):
                    features[fk]["status"] = s.get("feature_status")
                if features[fk]["name"] == fk and s.get("feature_name"):
                    features[fk]["name"] = s.get("feature_name")
            features[fk]["stories"].append(s)
        else:
            standalone.append(s)

    # ── Merge PI snapshot so ALL developer stories appear in the tree ─────────
    # sync_jira_features.py fetches every assigned story from Jira (active +
    # recently done) and caches them in .memory/feature-cache/pi-snapshot.json.
    # Without this merge, stories that are "In Progress" in Jira but haven't been
    # started via DevFlow are invisible in the feature tree.
    # NOTE: jira_prefixes is intentionally NOT extended here — the cross-project
    # filter must still reject stories from other Jira projects (e.g. BDATART-*)
    # that share the same assignee.
    pi = _load_pi_snapshot()
    pi_features: dict[str, Any] = pi.get("features") or {}

    # Resolve current developer's display name once — used to filter stories
    current_user: str = _current_user_display_name(pi)

    for pi_fk, pi_feat in pi_features.items():
        # ── Skip pseudo-feature groups (story-under-story parent relationships)
        # sync_jira_features.py marks genuine Features/Epics with is_real_feature=True.
        # Any entry without that flag is a story being used as a grouping key,
        # which would incorrectly show e.g. BDRSP-1705 as a Feature node.
        if not pi_feat.get("is_real_feature", False):
            continue

        # Only merge stories that belong to the same Jira project(s) as the
        # DevFlow stories.  Skip the whole feature if none of its stories match.
        pi_stories = [
            s for s in (pi_feat.get("stories") or [])
            if _is_same_jira_project(s.get("key", ""))
        ]
        if not pi_stories:
            continue

        if pi_fk in features:
            # Feature already has DevFlow stories — merge in any missing stories
            for pi_s in pi_stories:
                bucket = _pi_story_bucket(pi_s)
                if bucket == "completed":
                    features[pi_fk]["completed_stories"] = _merge_unique_issues(
                        features[pi_fk]["completed_stories"], [pi_s]
                    )
                elif bucket == "in_progress":
                    features[pi_fk]["in_progress_stories"] = _merge_unique_issues(
                        features[pi_fk]["in_progress_stories"], [pi_s]
                    )
                else:
                    features[pi_fk]["pending_stories"] = _merge_unique_issues(
                        features[pi_fk]["pending_stories"], [pi_s]
                    )
            # Backfill feature name/status if DevFlow didn't capture it
            if not features[pi_fk]["status"] and pi_feat.get("status"):
                features[pi_fk]["status"] = pi_feat["status"]
            if features[pi_fk]["name"] == pi_fk and pi_feat.get("name"):
                features[pi_fk]["name"] = pi_feat["name"]
        else:
            # Feature has NO DevFlow stories yet — add it from the pi-snapshot
            completed_p  = [s for s in pi_stories if _pi_story_bucket(s) == "completed"]
            inprogress_p = [s for s in pi_stories if _pi_story_bucket(s) == "in_progress"]
            pending_p    = [s for s in pi_stories if _pi_story_bucket(s) == "pending"]
            features[pi_fk] = {
                "key": pi_fk,
                "name": pi_feat.get("name") or pi_fk,
                "status": pi_feat.get("status") or "",
                "desc": "",
                "stories": [],          # no DevFlow stories yet
                "completed_stories": completed_p,
                "in_progress_stories": inprogress_p,
                "pending_stories": pending_p,
            }

    # ── Build extra-subtasks map BEFORE the rendering loop ───────────────────
    # sync_jira_features.py now puts story-under-story items (sub-tasks of
    # stories) into unparented with a "_parent_key" field instead of creating
    # fake feature groups.  We collect them here and inject them into the
    # correct parent story's subtask list during rendering.
    pi_unparented_raw = pi.get("unparented") or []
    _extra_subtasks: dict[str, list[dict[str, Any]]] = {}
    pi_unparented: list[dict[str, Any]] = []
    for _pi_s in pi_unparented_raw:
        _pk_field = _pi_s.get("_parent_key")
        if _pk_field:
            _extra_subtasks.setdefault(_pk_field, []).append(_pi_s)
        else:
            pi_unparented.append(_pi_s)

    html_parts: list[str] = []

    # ── Feature groups ────────────────────────────────────────────────────────
    for fk, fg in features.items():
        feat_icon, feat_color = _status_icon(fg["status"])
        feat_url = _jira_url(fk)
        feat_name_short = fg["name"][:90] + ("…" if len(fg["name"]) > 90 else "")

        completed  = fg["completed_stories"]
        inprogress = fg["in_progress_stories"]
        pending    = fg["pending_stories"]
        all_feature_stories = _merge_unique_issues(_merge_unique_issues(completed, inprogress), pending)

        # ── Remove cross-project stories (e.g. BDATART-* when tracking BDRSP-*)
        # Keep: same Jira project stories + any DevFlow-implemented story
        all_feature_stories = [
            s for s in all_feature_stories
            if _is_same_jira_project(s.get("key",""))
            or s.get("key","") in devflow_ids
        ]

        # ── Remove cancelled stories from the tree entirely ───────────────────
        all_feature_stories = [
            s for s in all_feature_stories
            if s.get("key","") not in CANCELLED_STORY_KEYS
        ]

        # ── Keep only stories assigned to the current developer ───────────────
        all_feature_stories = [
            s for s in all_feature_stories
            if _is_my_story(s, current_user, devflow_ids)
        ]

        shown_keys: set[str] = {sib.get("key", "") for sib in all_feature_stories}

        # ④ Any DevFlow stories not already shown (e.g. no sibling data yet)
        for df_s in fg["stories"]:
            if df_s["id"] not in shown_keys:
                sib_dict = {"key": df_s["id"], "summary": df_s.get("summary",""),
                            "status": df_s.get("jira_status") or df_s["status_label"],
                            "status_category": df_s.get("jira_status_category") or "",
                            "assignee": df_s.get("assignee") or "—", "updated": df_s["updated"]}
                all_feature_stories.append(sib_dict)

        # Recompute accurate counts after all merges
        done_count       = sum(1 for s in all_feature_stories if (s.get("status_category") or "").lower() == "done" or (s.get("status") or "").lower() in {"done","closed","resolved"})
        inprogress_count = sum(1 for s in all_feature_stories if (s.get("status_category") or "").lower() == "in progress")
        pending_count    = len(all_feature_stories) - done_count - inprogress_count

        # ── Sort stories: In Progress → Pending/To Do → Done ─────────────────
        _STATUS_SORT = {"in progress": 0, "in analysis": 1, "ready": 2, "to do": 3, "done": 9, "closed": 9, "resolved": 9}

        def _story_sort_key(s: dict[str, Any]) -> int:
            sc  = (s.get("status_category") or "").lower()
            sst = (s.get("status") or "").lower()
            if sc == "done" or sst in {"done", "closed", "resolved"}:
                return 9
            if sc == "in progress":
                return 0
            return next((_STATUS_SORT[k] for k in _STATUS_SORT if k in sst), 5)

        all_feature_stories.sort(key=_story_sort_key)

        # ── Render tree: Feature → Story → Subtask ───────────────────────────
        stories_html = f'<div class="tree-section-label">Stories ({len(all_feature_stories)})</div>'
        stories_html += _render_sibling_group(
            all_feature_stories, devflow_ids=devflow_ids,
            feature_stories=fg["stories"], extra_subtasks=_extra_subtasks
        )

        tree_id = _safe_dom_id(fk)
        html_parts.append(f'''
  <div class="feature-node" id="feat_{tree_id}">
    <div class="feature-header" onclick="toggleTree('feat_{tree_id}')">
      <span class="tree-toggle" id="toggle_feat_{tree_id}">▼</span>
      <span class="feature-type-pill">Feature</span>
      <a href="{feat_url}" target="_blank" class="feature-key">{fk}</a>
      <span class="feature-name">{feat_name_short}</span>
      <span class="feature-status" style="color:{feat_color};">{feat_icon} {fg["status"]}</span>
      <span class="feature-meta">{done_count} done · {inprogress_count} in progress · {pending_count} pending</span>
    </div>
    <div class="feature-children" id="children_feat_{tree_id}">
      <div class="tree-branch-line"></div>
      <div class="siblings-container">
        {stories_html}
      </div>
    </div>
  </div>''')

    # ── Standalone stories (no feature) ──────────────────────────────────────
    # Also include PI unparented stories not already covered above.
    # Apply the same cross-project filter so BDATART-* / MICDATAPL-* stories
    # that belong to other teams don't pollute the standalone section.
    # ── Standalone stories (no feature) ──────────────────────────────────────
    # Also include PI unparented stories not already covered above.
    # Apply the same cross-project + assignee filter used for feature groups.
    standalone_keys = {s["id"] for s in standalone}
    for pi_s in pi_unparented:
        pk = pi_s.get("key", "")
        if not pk or pk in standalone_keys:
            continue
        # Skip cancelled stories — hidden from the tree entirely
        if pk in CANCELLED_STORY_KEYS:
            continue
        # Skip stories from other projects
        if not _is_same_jira_project(pk):
            continue
        # Skip stories not assigned to the current developer
        if not _is_my_story(pi_s, current_user, devflow_ids):
            continue
        standalone.append({"_pi_only": True, **pi_s})
        standalone_keys.add(pk)

    if standalone:
        standalone_rows = ""
        for s in standalone:
            if s.get("_pi_only"):
                # PI-only story (no DevFlow run) — render as plain sibling
                sib_dict = {"key": s.get("key",""), "summary": s.get("summary",""),
                            "status": s.get("status",""), "status_category": s.get("status_category",""),
                            "assignee": s.get("assignee") or "—", "updated": s.get("updated","")}
                standalone_rows += _story_node(sib_dict, df_story=None)
            else:
                sib_dict = {"key": s["id"], "summary": s.get("summary",""),
                            "status": s.get("jira_status") or s["status_label"],
                            "status_category": s.get("jira_status_category") or "",
                            "assignee": s.get("assignee") or "—", "updated": s["updated"]}
                standalone_rows += _story_node(sib_dict, df_story=s)

        html_parts.append(f'''
  <div class="feature-node" id="feat_standalone">
    <div class="feature-header" onclick="toggleTree('feat_standalone')">
      <span class="tree-toggle" id="toggle_feat_standalone">▼</span>
      <span class="feature-type-pill" style="background:#21262d;color:#8b949e;">No Feature</span>
      <span class="feature-name" style="color:#8b949e;">Standalone Stories</span>
      <span class="feature-meta">{len(standalone)} stories</span>
    </div>
    <div class="feature-children" id="children_feat_standalone">
      <div class="tree-branch-line"></div>
      <div class="siblings-container">{standalone_rows}</div>
    </div>
  </div>''')

    return "\n".join(html_parts)


def _story_detail_tree(s: dict[str, Any]) -> str:
    """Render expanded detail for a DevFlow-implemented story."""
    timings   = s.get("stage_timings") or []
    mr_url    = s.get("mr_url") or ""
    mr_title  = s.get("mr_title") or ""
    files     = s.get("files_list") or []
    test_v    = s.get("test_verdict") or "—"
    ai_time   = s.get("ai_time") or "—"
    hu_time   = s.get("human_time") or "—"
    next_gate = s.get("next_gate") or ""
    conf      = s.get("confidence") or "—"
    subtasks  = s.get("subtasks") or []

    # Stage timeline rows
    stage_rows = ""
    for i, t in enumerate(timings):
        stage_rows += _stage_row(t, is_last=(i == len(timings) - 1))

    if not stage_rows and s["stage"] != "start":
        stage_rows = _stage_row({"stage": s["stage"], "actor": "ai", "elapsed_s": 0}, is_last=True)
    elif not stage_rows:
        stage_rows = '<div class="tree-stage"><span class="tree-connector">└─</span><span class="stage-label">📥 Start — Analysis complete</span></div>'

    # MR link
    mr_html = ""
    if mr_url:
        mr_html = f'<div class="detail-item">🔗 <a href="{mr_url}" target="_blank" style="color:#58a6ff;">MR: {mr_title or mr_url}</a></div>'
    elif next_gate:
        mr_html = f'<div class="detail-item">⏸ Next: <span style="color:#d29922;">{next_gate}</span></div>'

    # Files
    files_html = ""
    if files:
        file_list = "".join(f'<span class="file-chip">{f.split("/")[-1]}</span>' for f in files[:6])
        if len(files) > 6:
            file_list += f'<span class="file-chip" style="color:#8b949e;">+{len(files)-6} more</span>'
        files_html = f'<div class="detail-item">📁 {file_list}</div>'

    test_color = "#3fb950" if test_v == "passed" else "#f85149" if test_v == "failed" else "#8b949e"
    subtask_html = _subtask_list_html(subtasks)

    return f'''
    <div class="story-detail-tree">
      <div class="detail-grid">
        <div class="detail-item">🤖 AI: <b style="color:#a371f7;">{ai_time}</b></div>
        <div class="detail-item">👤 Human: <b style="color:#f78166;">{hu_time}</b></div>
        <div class="detail-item">🧪 Tests: <b style="color:{test_color};">{test_v}</b></div>
        <div class="detail-item">🔍 Code: <b style="color:#79c0ff;">{conf}</b></div>
      </div>
      {files_html}
      {mr_html}
      {subtask_html}
      <div class="stage-timeline">{stage_rows}</div>
    </div>'''


# ---------------------------------------------------------------------------
# HTML generation
# ---------------------------------------------------------------------------

def _badge(label: str, bg: str, color: str) -> str:
    return (f'<span style="background:{bg};color:{color};padding:2px 10px;'
            f'border-radius:12px;font-size:.78rem;font-weight:600;">{label}</span>')


def _confidence_badge(conf: str) -> str:
    colors = {"high": ("#1a4731","#3fb950"), "medium": ("#2a2a1a","#d29922"),
              "low": ("#4a1a1a","#f85149")}
    bg, fg = colors.get(conf, ("#1f2937","#8b949e"))
    return _badge(conf, bg, fg)


def _test_badge(verdict: str) -> str:
    if verdict == "passed":  return _badge("✅ Passed", "#1a4731", "#3fb950")
    if verdict == "failed":  return _badge("❌ Failed", "#4a1a1a", "#f85149")
    return _badge("—", "#21262d", "#8b949e")


def _mr_link_cell(mr_url: str, mr_title: str, story_id: str) -> str:
    if mr_url:
        label = f"#{story_id.split('-')[-1]} ✓"
        return f'<a href="{mr_url}" target="_blank" style="color:#58a6ff;text-decoration:none;">{label}</a>'
    return '<span style="color:#8b949e;">—</span>'


def _progress_bar(pct: int) -> str:
    color = "#3fb950" if pct == 100 else "#388bfd" if pct >= 60 else "#d29922"
    return (f'<div style="background:#21262d;border-radius:4px;height:6px;width:80px;">'
            f'<div style="background:{color};width:{pct}%;height:100%;border-radius:4px;"></div></div>'
            f'<span style="font-size:.75rem;color:#8b949e;margin-left:6px;">{pct}%</span>')


def generate_html(stories: list[dict[str, Any]]) -> str:
    total       = len(stories)
    ai_impl     = sum(1 for s in stories if s["stage"] != "start" or s["approvals"] > 0)
    in_progress = sum(1 for s in stories if s["status_label"] not in ("PR Created","Merged"))
    pr_created  = sum(1 for s in stories if s["status_label"] in ("PR Created","Merged"))
    total_ai_s  = sum(s.get("raw_ai_s", 0) for s in stories)
    avg_ai_s    = total_ai_s / max(total, 1)

    total_ai_h  = f"{total_ai_s/3600:.1f}h" if total_ai_s >= 3600 else f"{total_ai_s/60:.0f}m"
    avg_ai_fmt  = _fmt_duration(avg_ai_s)
    generated   = datetime.now().strftime("%Y-%m-%d %H:%M")

    # ── Auto-detected project info ────────────────────────────────────────────
    proj = project_info()
    proj_name  = proj["name"]                          # cdp-linking-middleware
    proj_short = proj["short"]                         # CDP-LMW  (auto)
    proj_lang  = proj["language"].title() or "Code"   # Java
    proj_label = proj["label"] or proj_name            # Spring Boot (Maven)

    # ── Stats cards ──────────────────────────────────────────────────────────
    def card(val: str, label: str, color: str = "#e6edf3") -> str:
        return f'''
        <div class="stat-card">
          <div class="stat-val" style="color:{color};">{val}</div>
          <div class="stat-lbl">{label}</div>
        </div>'''

    stats_html = (
        card(str(total),      "TOTAL STORIES",      "#e6edf3") +
        card(str(ai_impl),    "DEVFLOW STORIES",    "#58a6ff") +
        card(str(in_progress),"IN PROGRESS",         "#d29922") +
        card(str(pr_created), "PR CREATED",          "#3fb950") +
        card(total_ai_h,      "TOTAL AI TIME",       "#a371f7") +
        card(avg_ai_fmt,      "AVG PER STORY",       "#79c0ff")
    )

    # ── Table rows ───────────────────────────────────────────────────────────
    rows_html = ""
    for i, s in enumerate(stories):
        alt = "background:#0d1117;" if i % 2 == 0 else "background:#161b22;"
        rows_html += f'''
        <tr style="{alt}" class="story-row" onclick="window.open('{s["jira_url"]}','_blank')">
          <td><a href="{s["jira_url"]}" target="_blank" class="story-link">{s["id"]}</a></td>
          <td><span class="proj-badge">{proj_short}</span></td>
          <td style="color:#8b949e;font-size:.85rem;">{s["feature_key"]}</td>
          <td><span class="agent-badge agent-devflow">DevFlow</span></td>
          <td style="color:#a371f7;">{s["ai_time"]}</td>
          <td>{s["approvals"] if s["approvals"] else "—"}</td>
          <td>{_confidence_badge(s["confidence"])}</td>
          <td style="color:#8b949e;font-size:.85rem;">{s["updated"]}</td>
          <td>{_mr_link_cell(s["mr_url"], s["mr_title"], s["id"])}</td>
          <td>{_badge(s["status_label"], s["status_bg"], s["status_color"])}</td>
        </tr>'''

    # ── Full HTML ─────────────────────────────────────────────────────────────
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>DevFlow Analytics — {proj_name}</title>
<style>
  *{{box-sizing:border-box;margin:0;padding:0;}}
  body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
    background:#0d1117;color:#e6edf3;min-height:100vh;}}

  /* ── Top header ── */
  .top-bar{{background:#010409;border-bottom:1px solid #21262d;padding:10px 32px;
    display:flex;align-items:center;justify-content:space-between;}}
  .top-bar .pill{{background:#21262d;border:1px solid #30363d;border-radius:20px;
    padding:4px 12px;font-size:.75rem;color:#8b949e;letter-spacing:.06em;}}
  .top-bar .live-dot{{width:8px;height:8px;background:#3fb950;border-radius:50%;
    display:inline-block;margin-right:6px;animation:pulse 2s infinite;}}
  @keyframes pulse{{0%,100%{{opacity:1;}}50%{{opacity:.4;}}}}

  /* ── Hero ── */
  .hero{{text-align:center;padding:48px 32px 32px;}}
  .hero h1{{font-size:2.4rem;font-weight:700;letter-spacing:-.02em;}}
  .hero h1 span{{background:linear-gradient(135deg,#58a6ff,#a371f7);
    -webkit-background-clip:text;-webkit-text-fill-color:transparent;}}
  .hero .subtitle{{color:#8b949e;margin-top:8px;font-size:.95rem;}}

  /* ── Stats ── */
  .stats-row{{display:flex;gap:16px;padding:0 32px 32px;flex-wrap:wrap;justify-content:center;}}
  .stat-card{{background:#161b22;border:1px solid #30363d;border-radius:10px;
    padding:20px 28px;flex:1;min-width:140px;max-width:200px;text-align:center;
    transition:border-color .2s;cursor:default;}}
  .stat-card:hover{{border-color:#58a6ff;}}
  .stat-val{{font-size:2rem;font-weight:700;line-height:1;}}
  .stat-lbl{{font-size:.7rem;color:#8b949e;margin-top:6px;letter-spacing:.08em;}}

  /* ── Table ── */
  .table-wrap{{padding:0 32px 40px;overflow-x:auto;}}
  .section-title{{color:#8b949e;font-size:.8rem;letter-spacing:.08em;
    margin-bottom:12px;text-transform:uppercase;}}
  table{{width:100%;border-collapse:collapse;font-size:.88rem;min-width:900px;}}
  thead tr{{background:#161b22;}}
  th{{padding:12px 14px;text-align:left;color:#8b949e;font-weight:500;
    font-size:.78rem;letter-spacing:.06em;text-transform:uppercase;
    border-bottom:1px solid #21262d;white-space:nowrap;}}
  td{{padding:12px 14px;border-bottom:1px solid #161b22;vertical-align:middle;}}
  .story-row{{transition:background .15s;cursor:pointer;}}
  .story-row:hover td{{background:#1c2128 !important;}}
  .story-link{{color:#58a6ff;text-decoration:none;font-weight:600;font-size:.9rem;}}
  .story-link:hover{{text-decoration:underline;}}

  /* ── Badges ── */
  .proj-badge{{background:#1f2937;color:#79c0ff;border:1px solid #30363d;
    padding:2px 10px;border-radius:6px;font-size:.78rem;font-weight:600;}}
  .agent-badge{{padding:2px 10px;border-radius:12px;font-size:.78rem;font-weight:600;}}
  .agent-devflow{{background:#1a2a4a;color:#58a6ff;border:1px solid #1f6feb;}}
  .agent-manual{{background:#2a1a1a;color:#f85149;border:1px solid #6e2b2b;}}

  /* ── Tree view ── */
  .tree-section{{padding:0 32px 40px;}}
  .tree-tabs{{display:flex;gap:0;margin-bottom:0;border-bottom:1px solid #30363d;}}
  .tab-btn{{padding:8px 20px;background:none;border:none;color:#8b949e;cursor:pointer;
    font-size:.88rem;border-bottom:2px solid transparent;transition:all .15s;}}
  .tab-btn.active{{color:#e6edf3;border-bottom-color:#58a6ff;}}
  .tab-btn:hover{{color:#e6edf3;}}
  .tab-content{{display:none;padding-top:20px;}}
  .tab-content.active{{display:block;}}

  .feature-node{{margin-bottom:12px;border:1px solid #21262d;border-radius:8px;
    overflow:hidden;}}
  .feature-header{{display:flex;align-items:center;gap:10px;padding:12px 16px;
    background:#161b22;cursor:pointer;flex-wrap:wrap;transition:background .15s;}}
  .feature-header:hover{{background:#1c2128;}}
  .tree-toggle{{color:#8b949e;font-size:.8rem;transition:transform .2s;min-width:14px;}}
  .feature-type-pill{{background:#2d1b69;color:#a371f7;border:1px solid #8957e5;
    padding:1px 8px;border-radius:10px;font-size:.72rem;font-weight:600;white-space:nowrap;}}
  .feature-key{{color:#a371f7;font-weight:700;font-size:.92rem;text-decoration:none;white-space:nowrap;}}
  .feature-key:hover{{text-decoration:underline;}}
  .feature-name{{color:#e6edf3;font-size:.88rem;flex:1;}}
  .feature-status{{font-size:.82rem;white-space:nowrap;}}
  .feature-meta{{color:#484f58;font-size:.75rem;white-space:nowrap;margin-left:auto;}}

  .feature-children{{padding:0 0 8px 0;background:#0d1117;}}
  .tree-branch-line{{width:2px;background:#21262d;margin:0 0 0 28px;height:8px;}}
  .siblings-container{{padding:0 12px 4px 28px;}}
  .tree-section-label{{color:#484f58;font-size:.72rem;letter-spacing:.08em;
    text-transform:uppercase;padding:8px 4px 4px;}}
  .tree-sibling{{display:flex;align-items:center;gap:8px;padding:6px 10px;
    border-radius:6px;margin-bottom:2px;flex-wrap:wrap;cursor:pointer;
    border-left:2px solid transparent;transition:all .12s;}}
  .tree-sibling:hover{{background:#161b22;}}
  .story-node{{border-left:2px solid transparent;border-radius:6px;margin-bottom:4px;}}
  .story-node.current-story{{border-left-color:#388bfd;background:rgba(56,139,253,.07);}}
  .story-header{{display:flex;align-items:center;gap:8px;padding:7px 10px;
    border-radius:6px;cursor:pointer;transition:background .12s;}}
  .story-header:hover{{background:#161b22;}}
  .story-children{{margin-left:18px;padding:0 0 4px 10px;border-left:1px solid #21262d;}}
  .tree-key{{color:#58a6ff;font-weight:600;font-size:.85rem;text-decoration:none;
    white-space:nowrap;}}
  .tree-key:hover{{text-decoration:underline;}}
  .tree-summary{{color:#8b949e;font-size:.83rem;flex:1;}}
  .tree-meta{{color:#484f58;font-size:.75rem;white-space:nowrap;margin-left:auto;}}
  .devflow-badge{{background:#1a2a4a;color:#58a6ff;border:1px solid #1f6feb;
    padding:1px 7px;border-radius:10px;font-size:.72rem;}}

  .story-detail-tree{{margin:4px 0 8px 18px;background:#161b22;border:1px solid #21262d;
    border-radius:6px;padding:10px 14px;}}
  .detail-grid{{display:flex;gap:16px;flex-wrap:wrap;margin-bottom:8px;}}
  .detail-item{{font-size:.8rem;color:#8b949e;}}
  .detail-item b{{font-weight:600;}}
  .file-chip{{display:inline-block;background:#21262d;color:#79c0ff;border-radius:4px;
    padding:1px 6px;font-size:.72rem;margin:1px;}}
  .subtask-list{{margin:8px 0;border-top:1px solid #21262d;padding-top:6px;}}
  .subtask-row{{display:flex;align-items:center;gap:8px;padding:5px 0;font-size:.8rem;}}
  .subtask-indent{{color:#30363d;font-family:monospace;min-width:18px;}}
  .empty-subtasks{{color:#6e7681;font-size:.78rem;}}
  /* ── Subtask tree nodes ── */
  .subtasks-container{{padding:2px 0 4px 16px;border-left:1px solid #21262d;margin-left:12px;margin-top:2px;}}
  .subtask-tree-node{{display:flex;align-items:center;gap:7px;padding:3px 6px;
    border-radius:5px;font-size:.8rem;transition:background .1s;}}
  .subtask-tree-node:hover{{background:#161b22;}}
  .subtask-connector{{color:#30363d;font-family:monospace;min-width:18px;font-size:.8rem;}}
  .subtask-key{{color:#58a6ff;font-weight:600;font-size:.81rem;text-decoration:none;white-space:nowrap;}}
  .subtask-key:hover{{text-decoration:underline;}}
  .subtask-summary{{color:#8b949e;font-size:.79rem;flex:1;}}
  .stage-timeline{{margin-top:8px;border-top:1px solid #21262d;padding-top:6px;}}
  .tree-stage{{display:flex;align-items:center;padding:3px 0;font-size:.8rem;}}
  .tree-connector{{color:#30363d;font-family:monospace;margin-right:6px;min-width:18px;}}
  .stage-label{{color:#e6edf3;}}

  /* ── Footer ── */
  .footer{{text-align:center;padding:20px;color:#484f58;font-size:.8rem;
    border-top:1px solid #21262d;}}

  /* ── Empty state ── */
  .empty{{text-align:center;padding:60px;color:#484f58;}}
  .empty .icon{{font-size:3rem;margin-bottom:12px;}}
</style>
</head>
<body>

<div class="top-bar">
  <div>
    <span class="pill"><span class="live-dot"></span>ANALYTICS · REAL-TIME TRACKING</span>
  </div>
  <div style="color:#484f58;font-size:.8rem;">Generated: {generated}</div>
</div>

<div class="hero">
  <h1>DevFlow <span>Analytics</span></h1>
  <div class="subtitle">Jira &nbsp;→&nbsp; DevFlow &nbsp;→&nbsp; GitLab Integration Analytics &nbsp;|&nbsp; {proj_name}</div>
  <div style="color:#484f58;font-size:.8rem;margin-top:4px;">{proj_label}</div>
</div>

<div class="stats-row">
  {stats_html}
</div>

<div style="padding:0 32px;">
  <div class="tree-tabs">
    <button class="tab-btn active" id="tab-btn-table" onclick="switchTab('table')">📋 Table View</button>
    <button class="tab-btn" id="tab-btn-tree" onclick="switchTab('tree')">🌳 Feature Tree</button>
  </div>
</div>

<div id="tab-table" class="tab-content active">
<div class="table-wrap">
  <div class="section-title">Story Implementation Records</div>
  <table>
    <thead>
      <tr>
        <th>Ticket No.</th>
        <th>Project</th>
        <th>Feature</th>
        <th>Agent Used</th>
        <th>AI Time</th>
        <th>Approvals</th>
        <th>Code Confidence</th>
        <th>Last Updated</th>
        <th>MR Link</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      {rows_html if rows_html else f'<tr><td colspan="10" class="empty"><div class="icon">🤖</div><div>No stories implemented yet.</div></td></tr>'}
    </tbody>
  </table>
</div>
</div>

<div id="tab-tree" class="tab-content">
<div class="tree-section">
  <div class="section-title" style="margin-bottom:16px;">Feature → Stories → Subtasks / DevFlow Stages</div>
  {build_tree_html(stories)}
</div>
</div>

<div class="footer">
  DevFlow Automation Analytics &nbsp;·&nbsp; {proj_name} &nbsp;·&nbsp;
  <a href="repo-graph.html" style="color:#58a6ff;">Repo Graph</a>
</div>

<script>
function switchTab(tab) {{
  document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
  document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
  document.getElementById('tab-btn-' + tab).classList.add('active');
  document.getElementById('tab-' + tab).classList.add('active');
}}
function toggleTree(id) {{
  var children = document.getElementById('children_' + id);
  var toggle   = document.getElementById('toggle_' + id);
  if (children.style.display === 'none') {{
    children.style.display = '';
    toggle.style.transform = 'rotate(0deg)';
    toggle.textContent = '▼';
  }} else {{
    children.style.display = 'none';
    toggle.style.transform = 'rotate(-90deg)';
    toggle.textContent = '▶';
  }}
}}
</script>

</body>
</html>'''


def _empty_state() -> str:
    return ""


def generate(out_path: Path = OUT_HTML) -> Path:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    stories = load_all_stories()
    html = generate_html(stories)
    out_path.write_text(html, encoding="utf-8")
    return out_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import sys
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else OUT_HTML
    path = generate(out)
    try:
        snapshot = json.loads(FEATURE_CACHE_FILE.read_text(encoding="utf-8")) if FEATURE_CACHE_FILE.exists() else {}
        total = snapshot.get("total_stories") or len([p for p in STORIES_DIR.glob("*.json") if p.is_file()])
    except Exception:
        total = len([p for p in STORIES_DIR.glob("*.json") if p.is_file()])
    print(f"✅ DevFlow Analytics generated → {path}")
    print(f"   Stories: {total}")
    print("   Jira:    live refresh enabled" if _live_jira_enabled() else "   Jira:    live refresh disabled")
    print(f"   Open:    http://localhost:8080/devflow-analytics.html")
