#!/usr/bin/env python3
"""Generate a project-specific AGENTS.md for the current repo.

Run this once after placing the Automation folder in a new project:
    python Automation/scripts/generate_agents_md.py

It auto-detects the project type and writes a tailored AGENTS.md
at the repository root.
"""
from __future__ import annotations
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "mcp-servers", "dev-mcp", "src"))

from langchain_helpers.repo_resolver import get_resolver
from langchain_helpers.project_detector import detect_project

def generate() -> None:
    resolver = get_resolver()
    detector = detect_project(resolver.repo_root)
    repo = resolver.repo_root
    agents_path = repo / "AGENTS.md"

    # Build tech stack description
    tech_map = {
        "spring_boot_maven": "Spring Boot · Maven · Java",
        "java_gradle":       "Java · Gradle",
        "django":            "Python · Django",
        "fastapi":           "Python · FastAPI",
        "golang":            "Go",
        "rust":              "Rust · Cargo",
        "dotnet":            ".NET · C#",
        "nextjs":            "TypeScript · Next.js · React",
        "react":             "TypeScript · React",
        "vue":               "TypeScript · Vue.js",
        "angular":           "TypeScript · Angular",
        "nuxt":              "TypeScript · Nuxt.js · Vue",
        "nodejs_express":    "JavaScript/TypeScript · Node.js · Express",
    }
    tech_label = tech_map.get(detector.project_type, detector.label)

    # Source layout description
    src_sections = "\n".join(f"- `{g.split('/**')[0]}/` — source files" for g in detector.source_globs[:5])

    content = f"""# AGENTS.md

## Scope
This file applies to the entire repository unless a deeper `AGENTS.md` overrides or narrows guidance.

## Project overview
**Project type:** {detector.label}  
**Language:** {detector.language}  
**Category:** {detector.category}  
**Tech stack:** {tech_label}

> This file was generated by `Automation/scripts/generate_agents_md.py`.
> Update it to reflect the actual project architecture.

## Source layout
{src_sections}

## Build and validation

```bash
# Run tests
{detector.test_command}

# Run targeted tests only (preferred)
{detector.targeted_test_template.replace("{CLASSES}", "ClassName1,ClassName2")}

# Build
{detector.build_command}
```

## General coding rules
- Follow the existing project structure, naming conventions, and patterns.
- Keep changes small and scoped to the story/ticket being implemented.
- Do not introduce unrelated refactors, formatting churn, or dependency changes.
- Add or update tests for any changed business logic.
- Do not leave unused imports, debug logs, TODOs, or commented-out code.

## Logging rules
- Use the project's existing logging framework.
- Do not log passwords, secrets, tokens, or sensitive user data.

## Error handling
- Prefer typed/specific exceptions over generic ones.
- Preserve the original cause when wrapping exceptions.
- Do not swallow exceptions silently.

## Tests
- Add or update tests for changed business logic.
- Keep tests near the mirrored production package.
- Prefer descriptive test names and focused assertions.

## Automation performance hints
See `Automation/.memory/codebase-index.json` for pre-indexed file paths and test command patterns.

## More specific guidance
Add nested `AGENTS.md` files per package/module as needed.
"""

    agents_path.write_text(content, encoding="utf-8")
    print(f"✅  Written: {agents_path}")
    print(f"    project_type : {detector.project_type}")
    print(f"    language     : {detector.language}")
    print(f"    category     : {detector.category}")
    print(f"    test_command : {detector.test_command}")

if __name__ == "__main__":
    generate()

