#!/usr/bin/env python3
"""One-command Automation setup for any project.

Run this after copying the Automation folder to a new repository:

    python Automation/scripts/setup_project.py

What it does:
  1. Auto-detects project type (Spring Boot, React, Vue, Django, Go, etc.)
  2. Generates AGENTS.md at repo root
  3. Generates a project-specific copilot-instructions.md
  4. Builds the FAISS code index for fast semantic search
  5. Writes .memory/project-profile.json (used by all MCP tools)
  6. Validates .env.local exists and lists required variables
"""
from __future__ import annotations
import sys, os, json, time

# Add dev-mcp src to path
_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_HERE, "..", "mcp-servers", "dev-mcp", "src"))

from langchain_helpers.repo_resolver import get_resolver
from langchain_helpers.project_detector import detect_project

def step(n: int, msg: str) -> None:
    print(f"\n{'='*55}")
    print(f"  Step {n}: {msg}")
    print(f"{'='*55}")

def ok(msg: str) -> None:
    print(f"  ✅  {msg}")

def warn(msg: str) -> None:
    print(f"  ⚠️   {msg}")

def main() -> None:
    print("\n🚀  Automation Project Setup")
    print("    Auto-detecting project type and configuring...\n")

    # ── Detect ──────────────────────────────────────────────────────────────────
    resolver = get_resolver()
    detector = detect_project(resolver.repo_root)
    repo     = resolver.repo_root

    ok(f"Repo root     : {repo}")
    ok(f"Project type  : {detector.label}")
    ok(f"Language      : {detector.language}")
    ok(f"Category      : {detector.category}")
    ok(f"Package mgr   : {detector.package_manager}")

    # ── Step 1: Save project profile ────────────────────────────────────────────
    step(1, "Saving project profile to .memory/")
    profile = {
        "_meta": {
            "description": "Auto-detected project profile. Re-generated by setup_project.py.",
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        },
        **detector.summary(),
    }
    profile_path = resolver.memory_path("project-profile.json")
    profile_path.write_text(json.dumps(profile, indent=2), encoding="utf-8")
    ok(f"Written: {profile_path.relative_to(repo)}")

    # ── Step 2: Generate AGENTS.md ───────────────────────────────────────────────
    step(2, "Generating AGENTS.md")
    try:
        from scripts.generate_agents_md import generate  # type: ignore
        generate()
    except Exception:
        # Fallback: run the script directly
        script = os.path.join(_HERE, "generate_agents_md.py")
        if os.path.exists(script):
            import importlib.util
            spec = importlib.util.spec_from_file_location("gen_agents", script)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            mod.generate()
        else:
            warn("generate_agents_md.py not found — skipping")

    # ── Step 3: Generate .github/copilot-instructions.md ────────────────────────
    step(3, "Generating .github/copilot-instructions.md")
    _write_copilot_instructions(repo, detector)

    # ── Step 4: Build FAISS code index ──────────────────────────────────────────
    step(4, "Building FAISS code index (first time only, ~30s)")
    try:
        from langchain_helpers.code_vectorstore import CodeVectorStore
        vs = CodeVectorStore(repo_path=str(repo))
        if vs.is_index_fresh():
            ok("Index already fresh — skipping rebuild")
        else:
            t = time.time()
            success = vs.rebuild()
            elapsed = round(time.time() - t, 1)
            if success:
                ok(f"Index built in {elapsed}s — future searches will be ~5ms")
            else:
                warn("Index build failed — ripgrep fallback will be used")
    except Exception as exc:
        warn(f"FAISS indexing skipped: {exc}")

    # ── Step 5: Check .env.local ─────────────────────────────────────────────────
    step(5, "Checking .env.local")
    _check_env(resolver, detector)

    # ── Done ─────────────────────────────────────────────────────────────────────
    print(f"\n{'='*55}")
    print("  ✅  Setup complete!")
    print(f"{'='*55}")
    print(f"""
  Project   : {detector.label}
  Test cmd  : {detector.test_command}
  Build cmd : {detector.build_command}

  Next steps:
    1. Fill in Automation/.env.local with your credentials
    2. Restart the MCP server (Automation/mcp_start.sh)
    3. Start a story with: dev_implement_story(jira_id="YOUR-ID")
""")

def _write_copilot_instructions(repo, detector) -> None:
    """Write a project-type-aware copilot-instructions.md."""
    github_dir = repo / ".github"
    github_dir.mkdir(exist_ok=True)
    path = github_dir / "copilot-instructions.md"

    targeted_example = detector.targeted_test_template.replace("{CLASSES}", "ClassA,ClassB")
    
    content = f"""# Copilot DevFlow Gate

These instructions are mandatory for this repository.

When the user provides only a Feature key or asks to create stories for a Feature:

1. In DevFlow, call `dev_bootstrap_feature_stories(feature_key=<key>, confirm_create=false)`.
2. In Jira-only profile, call `jira_bootstrap_feature_stories(feature_key=<key>, confirm_create=false)`.
3. The bootstrap flow must learn the Feature, discover existing child stories, read Confluence/ADR cache, read repo knowledge graph, treat the Feature key as `parent_key`, and generate story payloads when no stories exist.
4. If existing stories are found, show the sprint-wise plan and ask whether to fill missing phases.
5. If sprint is missing or ambiguous, ask which sprint to attach before preview/create; accept `sprint_id`, `sprint_name`, or `sprint_by_phase`; never guess.
6. If the bootstrap preview is ready, show it and ask for explicit approval.
7. Create stories only after the preview is accepted and the user explicitly approves `confirm_create=true`.

When the user asks to implement, start, work on, update, or modify a Jira story:

1. Do not read source files first.
2. Do not edit source files first.
3. Do not create branches, commits, pushes, or merge requests first.
4. Call MCP tool `dev_implement_story` from `dev-mcp` with `stage="start"` and the Jira key.
5. Show the returned parent Feature context, completed sibling stories, Jira story context, codebase analysis, proposed Jira update, and stop point.
6. Ask for approval before `stage="apply_story_update"`.
7. After Jira update, ask for approval before code changes.
8. Start code changes only after the user explicitly approves the returned code-change gate.
9. After code changes are complete, call `dev_implement_story` with `stage="after_code_changes"`, `code_changes_done=true`, and `run_tests=true`. This runs tests autonomously via subprocess inside the MCP server — no IDE terminal step needed. Show the `autonomous_test_execution` result (verdict, exit code, failure analysis) to the user. If tests fail, fix and repeat before proceeding.
10. Ask for approval before `stage="create_mr"`.

If `dev_implement_story` is unavailable, disconnected, or times out, stop and report the MCP problem. Do not fall back to normal implementation.

For Jira-only story update/refine work, use `jira_feature_context` before any `jira_refine_story` write and preserve the formatting style in both the proposal and the approved Description.

---

## Project Info (Auto-detected)

- **Project type:** {detector.label}
- **Language:** {detector.language}
- **Category:** {detector.category}
- **Package manager:** {detector.package_manager}

---

## Performance Rules

### Parallel Execution at stage="start"
At `stage="start"`, always launch these operations in parallel — do NOT wait for one before starting the next:
- Jira story fetch
- Codebase scan (semantic + grep)
- LangGraph memory load

### Test Execution — Targeted Tests Only
- **Never run full test suite** unless the user explicitly asks for it.
- Always pass `test_command` with only the impacted test classes when calling `dev_implement_story` with `run_tests=true`.
- Use this pattern for targeted tests:
  ```
  {targeted_example}
  ```
- Only escalate to full `{detector.test_command}` if targeted tests pass and a regression check is explicitly requested.

### Confluence / External Docs Caching
- Before reading any Confluence page or external documentation URL, check `Automation/.memory/confluence-cache/` for a cached version.
- Respect TTL: if `cached_at` is within 24 hours, use the cache — do not re-fetch.

### Codebase Index
- Before running a broad search, check `Automation/.memory/codebase-index.json` for pre-indexed file paths.
- After discovering new relevant files, update `Automation/.memory/codebase-index.json` with the new paths.
"""
    path.write_text(content, encoding="utf-8")
    ok(f"Written: .github/copilot-instructions.md ({detector.label})")

def _check_env(resolver, detector) -> None:
    """Check .env.local and list missing required variables."""
    env_path = resolver.env_file
    required = ["JIRA_BASE_URL", "JIRA_USERNAME", "JIRA_API_TOKEN"]
    optional = ["GITLAB_TOKEN", "OPENAI_API_KEY", "GITLAB_URL", "GITLAB_PROJECT_ID"]

    if not env_path or not env_path.exists():
        warn(f".env.local not found. Create it at: {resolver.automation_dir}/.env.local")
        print("  Required variables:")
        for v in required:
            print(f"    {v}=<your-value>")
        optional_str = "  Optional:\n" + "\n".join(f"    {v}=" for v in optional)
        print(optional_str)
        return

    env_content = env_path.read_text(encoding="utf-8")
    missing = [v for v in required if v not in env_content]
    present = [v for v in required if v in env_content]

    for v in present:
        ok(f"{v} ✓")
    for v in missing:
        warn(f"{v} — MISSING in {env_path.name}")

    if not missing:
        ok(f"All required variables present in {env_path.name}")

if __name__ == "__main__":
    main()
